apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: trains
  namespace: trains
spec:
  patchesJSON6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: trains-agent
      namespace: trains
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/command/2
        value:
          - "apt-get update ;
             apt-get install -y curl python3-pip git;
             curl -sSL https://get.docker.com/ | sh ;
             python3 -m pip install -U pip ;
             python3 -m pip install trains-agent{{ .Values.agent.agentVersion}} ;
             TRAINS_AGENT_K8S_HOST_MOUNT=/root/.trains:/root/.trains trains-agent daemon"
