---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trains
  namespace: trains
spec:
  releaseName: trains
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: allegroai
        namespace: flux-system
      chart: trains-server-chart
      version: "0.16.1+1"
  values:
    trains:
      nodeSelector: "app: trains"
    agent:
      agentVersion: "==0.16.2rc0"
      numberOfTrainsAgents: 1
      nvidiaGpusPerAgent: 1
      defaultBaseDocker: "nvidia/cuda"
      trainsApiHost: "http://trains.namecheapcloud.net:30008"
      trainsWebHost: "http://trains.namecheapcloud.net:30080"
      trainsFilesHost: "http://trains.namecheapcloud.net:30081"
      trainsAccessKey: "HDUSYJ0T2V6W9GX4ZESL"
      trainsSecretKey: "e!@ys(DMZhZ!6RzV+ERAXKnOY8xT!Z2hb%-=w3c-SgA1=O%6ej"
