apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: trains-configs
  namespace: trains
spec:
  encryptedData:
    trainsAccessKey: AgCmTlJVp8TX3f0WAsSZx3xQfoSv5NnlX4le2KCcmR9opEPNXY6UTfkZTFckKas6wv4aWIzb5WCol6KhCVacwcEmlojxt1IR03XZO95vvW3BMsg9aDuGOL0YvEA0qW4KamAbayWjOwReK/6Z2JsRb8hz5u6Gn6TXa/E7DWUBZK+vKzj6AyedvhoS+b5U3J0XMqkORocegknt/nCozEcNg6O2pvAoOhmE5im/MpMJAsc5I38OIgR57CSXAFEIb66A0uIZomLC08387rBjYLxtXSSY5jSHdMXSp4AnllFDhWpKGDsc3ol2j1+nhcHOGuATOfL5zS4G0qYKVI2KkuO4pbFcH86YxzmLsSFHJRIm1YwqcrLvgjK/eOx0b5B5wHDZWHObkU8sj3wdN+E1SczNZSVWTlM8qaVuTyDBf/Ey4uoKty0kqnbmBcbj/mgV5UmFsiFadK7DCSSzsY+4ZmipcOznGSiAo6j697YKnV1tD230FKLen0PaxQD0LPFMpcVveOXUSvAFZzoU603JnOOrM2c70t32WkQFxlshgkpVsDT+bUGk1q8OokIKyq4SnYDGFPOGRks6vUseoMkHr7s2iI+uROHTowvmhFqGKuxNqhyy9QzhrmllNrhShQQswdiOKOSeFjQEZl9BullRQrdpzF90H3lF4kEk0R6SSVEEsnBEmje/ObJFMKSZV8KyO4V09t9U/N/y5v0vkzfP2zIlpOwiPCROksg=
    trainsSecretKey: AgBLEptaiZPVR+QxXyZTSHXhdv+PK6JlzFgQLZixT4Xv3arZzdYe3Qfw2F1so34J3cBWGF4VjDWtm0S+e+W65d894Dv0ojXjvJyP0ukhXU7DgbDjxTkGaSRR/KWx04czI1mxy5mpx97kqSyTdRsvY1PK2iZtRtC+DSwNhf9xHTRORT+Nga+WWHhNqg6Y1unDMneL0q8NvUYqXncbbqyafGFcOPgJPCKeEqwqx6sO4Of6CQYKeTwAgz3WA4rIvum2ki3RPlpDSEhd57HDFUHcQEJSXaCPXGydkMFRZxou92lW0B4Dh2vqCvZRRJHhY3eDjxxyJCMO2f1nJDWaPdatzQqdowMZRMmSUBaYuTxpJqGUyxnmOAts1TkSWMy6xcjy3/nJKzAUIj8zhAQmwa6wmOCGTbifZ/fQoEK2miE9uXyBXY6IFBhLs8K2xLljzOuA/6WcmeQQmPFVru6GklDEmzT1Po6LsLYeowP+yLZpiIr2+Kl3GHPvUy8Kov871lnIxKhq/xYc0jwz4rnO8pfsIrSuDRHdRjIDQ0bbmdCtc40MZxfsLwfc310gzG2ewwhCK67vEeEduOk6EU/mLPcIcd+mMf9TPkpM8SHv2PD+uyuHPbgEBx2sSbwtForvlsTC8Q5hjIYvUVty7wJIBdk/zY+ePMUaRUx8GCA7dPq6QgM0844ideyhymxJQDa/EL25Tz/U53RAMyEtKrD7SHypddqHsaYTbDsPwEEIrb6LLO24DLY=
  template:
    metadata:
      creationTimestamp: null
      name: trains-configs
      namespace: trains
