apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: github
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/valeriano-manassero/trains-server-k8s
  ref:
    branch: cluster-test
