apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clearml
  namespace: clearml
spec:
  interval: 5m
  releaseName: clearml
  chart:
    spec:
      chart: clearml-server-cloud-ready
      sourceRef:
        kind: HelmRepository
        name: allegroai
        namespace: flux-system
      version: "2.0.2+1"
      interval: 1m
