apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clearml
  namespace: clearml
spec:
  interval: 5m
  releaseName: clearml
  chart:
    spec:
      chart: clearml
      sourceRef:
        kind: HelmRepository
        name: valeriano-manassero
        namespace: flux-system
      version: "0.1.1"
      interval: 1m
  values:
    apiserver:
      service:
        type: NodePort
        port: 8008
      storage:
        logs:
          class: "local-path"
          size: 10Gi
        config:
          class: "local-path"
          size: 1Gi

    fileserver:
      service:
        type: NodePort
        port: 8081
      storage:
        data:
          class: "local-path"
          size: 50Gi
        logs:
          class: "local-path"
          size: 5Gi

    webserver:
      service:
        type: NodePort
        port: 80
    
    agentservices:
      storage:
        data:
          class: "local-path"
          size: 50Gi

    agentGroups:
      - name: agent-group0
        queues: "default"
        agentVersion: ""
        replicaCount: 4
        nvidiaGpusPerAgent: 0
        clearmlApiHost: "http://clearml-apiserver:8008"
        clearmlWebHost: "http://clearml-webserver"
        clearmlFilesHost: "http://clearml-fileserver:8081"
        clearmlConfig: |-
          sdk {
              aws {
                  s3 {
                      key: ""
                      secret: ""
                      region: ""
                      credentials: [
                          {
                              host: "minio.minio:9000"
                              key: "DEMOaccessKey"
                              secret: "DEMOsecretKey"
                              multipart: false
                              secure: false
                              region: ""
                          }
                      ]
                  }
                  boto3 {
                      pool_connections: 512
                      max_multipart_concurrency: 16
                  }
              }
              development {
                  default_output_uri: "s3://minio.minio:9000/clearml/"
              }
          }

        storage:
          data:
            class: "local-path"
            size: 50Gi

        image:
          repository: "nvidia/cuda"
          pullPolicy: IfNotPresent
          tag: "11.2.0-runtime"

      - name: agent-group1
        queues: "gpu"
        agentVersion: ""
        replicaCount: 1
        nvidiaGpusPerAgent: 1
        clearmlApiHost: "http://clearml-apiserver:8008"
        clearmlWebHost: "http://clearml-webserver"
        clearmlFilesHost: "http://clearml-fileserver:8081"
        clearmlConfig: |-
          sdk {
              aws {
                  s3 {
                      key: ""
                      secret: ""
                      region: ""
                      credentials: [
                          {
                              host: "minio.minio:9000"
                              key: "DEMOaccessKey"
                              secret: "DEMOsecretKey"
                              multipart: false
                              secure: false
                              region: ""
                          }
                      ]
                  }
                  boto3 {
                      pool_connections: 512
                      max_multipart_concurrency: 16
                  }
              }
              development {
                  default_output_uri: "s3://minio.minio:9000/clearml/"
              }
          }

        storage:
          data:
            class: "local-path"
            size: 50Gi

        image:
          repository: "nvidia/cuda"
          pullPolicy: IfNotPresent
          tag: "11.2.0-runtime"
