apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 5m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: "13.8.0"
      interval: 1m
  values:
    kubeStateMetrics:
      enabled: false
    alertmanager:
      persistentVolume:
        storageClass: "local-path"
    server:
      persistentVolume:
        storageClass: "local-path"
