apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 5m
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
      version: "0.7.1"
      interval: 1m
  values:
    controller:
      service:
        type: NodePort
