---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  releaseName: gpu-operator
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: flux-system
      chart: gpu-operator
      version: "1.2.0"
