---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: gpu-operator
      sourceRef:
        kind: HelmRepository
        name: gpu-operator
        namespace: flux-system
      version: "1.2.0"
      interval: 1m
