apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-operator
spec:
  interval: 5m
  releaseName: minio
  chart:
    spec:
      chart: minio-operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      version: "4.0.8"
      interval: 1m
  values:
    tenants:
      - name: minio1
        image:
          repository: minio/minio
          tag: RELEASE.2021-04-06T23-11-00Z
        scheduler:
          name: ""
        pools:
          - servers: 1
            volumesPerServer: 4
            size: 100Gi
            storageClassName: local-path
        secrets:
          name: minio1-secret
          accessKey: DEMOaccessKey
          secretKey: DEMOsecretKey
        metrics:
          enabled: false
          port: 9000
          secrets:
            name: console-secret
            passphrase: SECRETpassphrase
            salt: SECRETsalt
            accessKey: DEMOaccessKey
            secretKey: DEMOsecretKey
