---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  releaseName: minio
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      chart: minio
      version: "8.0.0"
  values:
    mode: standalone
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 300Gi
    buckets:
      - name: data
        policy: none
        purge: false
      - name: metastore
        policy: none
        purge: false
    accessKey: DEMOaccessKey
    secretKey: DEMOsecretKey
