apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trains
  namespace: trains
spec:
  interval: 5m
  releaseName: trains
  chart:
    spec:
      chart: ./trains-server-chart
      sourceRef:
        kind: GitRepository
        name: valeriano-manassero-trains
        namespace: flux-system
      interval: 1m
  values:
    trains:
      nodeSelector: "app: trains"
    agent:
      queues: "default"
      dockerMode: false
      numberOfTrainsAgents: 1
      nvidiaGpusPerAgent: 1
      defaultBaseDocker: "nvidia/cuda"
      trainsApiHost: "http://apiserver-service:8008"
      trainsWebHost: "http://webserver-service"
      trainsFilesHost: "http://fileserver-service:8081"
      awsAccessKeyId: DEMOaccessKey
      awsSecretAccessKey: DEMOsecretKey
      trainsConfig: |-
        sdk {
            aws {
                s3 {
                    key: ""
                    secret: ""
                    region: ""
                    credentials: [
                        {
                            host: "minio.minio:9000"
                            key: "DEMOaccessKey"
                            secret: "DEMOsecretKey"
                            multipart: false
                            secure: false
                            region: ""
                        }
                    ]
                }
                boto3 {
                    pool_connections: 512
                    max_multipart_concurrency: 16
                }
            }
            development {
                default_output_uri: "s3://minio.minio:9000/trains/"
            }
        }
